#
#  imageconsts.rb
#  MBImageConstants
#
#  Created by Michal Banasiak on 27.07.2013.
#  Copyright (c) 2013 Michal Banasiak. All rights reserved.
#  https://github.com/bananita
#

#!/usr/bin/env ruby

root = ARGV[0]

$stdout.reopen("#{root}/Pods/MBImageConstants/MBImageConstants.h",'w')

puts "//"
puts "//  MBImageConstants.h"
puts "//  MBImageConstants"
puts "//"
puts "//  Created by Michal Banasiak on 27.07.2013."
puts "//  Copyright (c) 2013 Michal Banasiak. All rights reserved."
puts "//  https://github.com/bananita"
puts "//"
puts
puts "// AUTO-GENERATED FILE.  DO NOT MODIFY."
puts
puts "/*"
puts " * This file was automatically generated by the"
puts " * MBImageConstants tool from the images it found."
puts " * It should not be modified by hand."
puts " */"
puts
puts

Dir.glob("#{root}/**/*.imageset") do |imageset|
    name = File.basename(imageset, ".imageset")
    define = name.gsub ' ', ''
    
    puts "// #{name}"
    puts "#define image_#{define} @\"#{name}\""
    puts
end

puts
puts "// AUTO-GENERATED FILE.  DO NOT MODIFY."

$stdout=STDOUT
